# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ml_service_pb2 as ml__service__pb2


class MLServiceStub(object):
    """Сервис для работы с ML моделями
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/ml_service.MLService/HealthCheck',
                request_serializer=ml__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ml__service__pb2.HealthCheckResponse.FromString,
                )
        self.GetAvailableModels = channel.unary_unary(
                '/ml_service.MLService/GetAvailableModels',
                request_serializer=ml__service__pb2.GetAvailableModelsRequest.SerializeToString,
                response_deserializer=ml__service__pb2.GetAvailableModelsResponse.FromString,
                )
        self.GetModels = channel.unary_unary(
                '/ml_service.MLService/GetModels',
                request_serializer=ml__service__pb2.GetModelsRequest.SerializeToString,
                response_deserializer=ml__service__pb2.GetModelsResponse.FromString,
                )
        self.TrainModel = channel.unary_unary(
                '/ml_service.MLService/TrainModel',
                request_serializer=ml__service__pb2.TrainModelRequest.SerializeToString,
                response_deserializer=ml__service__pb2.TrainModelResponse.FromString,
                )
        self.Predict = channel.unary_unary(
                '/ml_service.MLService/Predict',
                request_serializer=ml__service__pb2.PredictRequest.SerializeToString,
                response_deserializer=ml__service__pb2.PredictResponse.FromString,
                )
        self.RetrainModel = channel.unary_unary(
                '/ml_service.MLService/RetrainModel',
                request_serializer=ml__service__pb2.RetrainModelRequest.SerializeToString,
                response_deserializer=ml__service__pb2.RetrainModelResponse.FromString,
                )
        self.DeleteModel = channel.unary_unary(
                '/ml_service.MLService/DeleteModel',
                request_serializer=ml__service__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=ml__service__pb2.DeleteModelResponse.FromString,
                )
        self.GetDatasets = channel.unary_unary(
                '/ml_service.MLService/GetDatasets',
                request_serializer=ml__service__pb2.GetDatasetsRequest.SerializeToString,
                response_deserializer=ml__service__pb2.GetDatasetsResponse.FromString,
                )
        self.UploadDataset = channel.unary_unary(
                '/ml_service.MLService/UploadDataset',
                request_serializer=ml__service__pb2.UploadDatasetRequest.SerializeToString,
                response_deserializer=ml__service__pb2.UploadDatasetResponse.FromString,
                )
        self.DeleteDataset = channel.unary_unary(
                '/ml_service.MLService/DeleteDataset',
                request_serializer=ml__service__pb2.DeleteDatasetRequest.SerializeToString,
                response_deserializer=ml__service__pb2.DeleteDatasetResponse.FromString,
                )


class MLServiceServicer(object):
    """Сервис для работы с ML моделями
    """

    def HealthCheck(self, request, context):
        """Проверка статуса сервиса
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableModels(self, request, context):
        """Получить список доступных типов моделей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModels(self, request, context):
        """Получить список всех моделей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrainModel(self, request, context):
        """Обучить модель
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Получить предсказания
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrainModel(self, request, context):
        """Переобучить модель
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Удалить модель
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasets(self, request, context):
        """Получить список датасетов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDataset(self, request, context):
        """Загрузить датасет
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDataset(self, request, context):
        """Удалить датасет
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ml__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=ml__service__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetAvailableModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableModels,
                    request_deserializer=ml__service__pb2.GetAvailableModelsRequest.FromString,
                    response_serializer=ml__service__pb2.GetAvailableModelsResponse.SerializeToString,
            ),
            'GetModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModels,
                    request_deserializer=ml__service__pb2.GetModelsRequest.FromString,
                    response_serializer=ml__service__pb2.GetModelsResponse.SerializeToString,
            ),
            'TrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.TrainModel,
                    request_deserializer=ml__service__pb2.TrainModelRequest.FromString,
                    response_serializer=ml__service__pb2.TrainModelResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=ml__service__pb2.PredictRequest.FromString,
                    response_serializer=ml__service__pb2.PredictResponse.SerializeToString,
            ),
            'RetrainModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrainModel,
                    request_deserializer=ml__service__pb2.RetrainModelRequest.FromString,
                    response_serializer=ml__service__pb2.RetrainModelResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=ml__service__pb2.DeleteModelRequest.FromString,
                    response_serializer=ml__service__pb2.DeleteModelResponse.SerializeToString,
            ),
            'GetDatasets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasets,
                    request_deserializer=ml__service__pb2.GetDatasetsRequest.FromString,
                    response_serializer=ml__service__pb2.GetDatasetsResponse.SerializeToString,
            ),
            'UploadDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDataset,
                    request_deserializer=ml__service__pb2.UploadDatasetRequest.FromString,
                    response_serializer=ml__service__pb2.UploadDatasetResponse.SerializeToString,
            ),
            'DeleteDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDataset,
                    request_deserializer=ml__service__pb2.DeleteDatasetRequest.FromString,
                    response_serializer=ml__service__pb2.DeleteDatasetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml_service.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MLService(object):
    """Сервис для работы с ML моделями
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml_service.MLService/HealthCheck',
            ml__service__pb2.HealthCheckRequest.SerializeToString,
            ml__service__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAvailableModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml_service.MLService/GetAvailableModels',
            ml__service__pb2.GetAvailableModelsRequest.SerializeToString,
            ml__service__pb2.GetAvailableModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml_service.MLService/GetModels',
            ml__service__pb2.GetModelsRequest.SerializeToString,
            ml__service__pb2.GetModelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml_service.MLService/TrainModel',
            ml__service__pb2.TrainModelRequest.SerializeToString,
            ml__service__pb2.TrainModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml_service.MLService/Predict',
            ml__service__pb2.PredictRequest.SerializeToString,
            ml__service__pb2.PredictResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrainModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml_service.MLService/RetrainModel',
            ml__service__pb2.RetrainModelRequest.SerializeToString,
            ml__service__pb2.RetrainModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml_service.MLService/DeleteModel',
            ml__service__pb2.DeleteModelRequest.SerializeToString,
            ml__service__pb2.DeleteModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDatasets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml_service.MLService/GetDatasets',
            ml__service__pb2.GetDatasetsRequest.SerializeToString,
            ml__service__pb2.GetDatasetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml_service.MLService/UploadDataset',
            ml__service__pb2.UploadDatasetRequest.SerializeToString,
            ml__service__pb2.UploadDatasetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml_service.MLService/DeleteDataset',
            ml__service__pb2.DeleteDatasetRequest.SerializeToString,
            ml__service__pb2.DeleteDatasetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
